version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: readora_postgres
    environment:
      POSTGRES_USER: readora
      POSTGRES_PASSWORD: readora123
      POSTGRES_DB: readora_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: readora_redis
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: readora_search
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: readora_search_key

volumes:
  postgres_data: