export const COLORS = {
  primary:                '#446651',
  primaryContainer:       '#7b9e87',
  primaryFixed:           '#c6ebd1',
  primaryFixedDim:        '#abcfb6',
  onPrimary:              '#ffffff',
  onPrimaryContainer:     '#143523',
  background:             '#faf9f6',
  surface:                '#faf9f6',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow:    '#f4f4f0',
  surfaceContainer:       '#eeeeeb',
  surfaceContainerHigh:   '#e8e8e5',
  onSurface:              '#1a1c1a',
  onSurfaceVariant:       '#424843',
  outline:                '#727973',
  outlineVariant:         '#c1c8c1',
  error:                  '#ba1a1a',
  secondaryContainer:     '#d5e3d7',
  onSecondaryContainer:   '#3d4a41',
  secondaryFixed:         '#d8e6da',
}
